package autoqa.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;

import java.util.Map;

/**
 * Complete element identity captured by DOMEnricher at recording time.
 * Contains all candidate locators so LocatorResolver can try them in order.
 */
@JsonInclude(JsonInclude.Include.NON_NULL)
public class ElementInfo {

    @JsonProperty("tagName")
    private String tagName;

    @JsonProperty("id")
    private String id;

    @JsonProperty("name")
    private String name;

    @JsonProperty("className")
    private String className;

    /** CSS selector (shortest unique path generated by DOMEnricher). */
    @JsonProperty("css")
    private String css;

    /** Absolute XPath generated by DOMEnricher. */
    @JsonProperty("xpath")
    private String xpath;

    /** Visible text content (trimmed, first 200 chars). */
    @JsonProperty("text")
    private String text;

    /** Value attribute. */
    @JsonProperty("value")
    private String value;

    /** Input type attribute (e.g., "text", "password", "checkbox"). */
    @JsonProperty("type")
    private String type;

    /** All other HTML attributes as key→value map. */
    @JsonProperty("attributes")
    private Map<String, String> attributes;

    @JsonProperty("boundingBox")
    private BoundingBox boundingBox;

    public ElementInfo() {}

    // ── Getters ──────────────────────────────────────────────────────────

    public String              getTagName()    { return tagName; }
    public String              getId()         { return id; }
    public String              getName()       { return name; }
    public String              getClassName()  { return className; }
    public String              getCss()        { return css; }
    public String              getXpath()      { return xpath; }
    public String              getText()       { return text; }
    public String              getValue()      { return value; }
    public String              getType()       { return type; }
    public Map<String, String> getAttributes() { return attributes; }
    public BoundingBox         getBoundingBox(){ return boundingBox; }

    // ── Setters ──────────────────────────────────────────────────────────

    public void setTagName(String tagName)                 { this.tagName = tagName; }
    public void setId(String id)                           { this.id = id; }
    public void setName(String name)                       { this.name = name; }
    public void setClassName(String className)             { this.className = className; }
    public void setCss(String css)                         { this.css = css; }
    public void setXpath(String xpath)                     { this.xpath = xpath; }
    public void setText(String text)                       { this.text = text; }
    public void setValue(String value)                     { this.value = value; }
    public void setType(String type)                       { this.type = type; }
    public void setAttributes(Map<String, String> attrs)   { this.attributes = attrs; }
    public void setBoundingBox(BoundingBox boundingBox)    { this.boundingBox = boundingBox; }

    /** True if this element info has at least one usable locator. */
    public boolean hasAnyLocator() {
        return (id != null && !id.isBlank())
            || (name != null && !name.isBlank())
            || (css  != null && !css.isBlank())
            || (xpath != null && !xpath.isBlank());
    }

    @Override
    public String toString() {
        return String.format("ElementInfo{tag='%s', id='%s', css='%s'}", tagName, id, css);
    }
}
